### ISSUE TITLE
Adding IOSurface Backing to generated CVPixelBuffer

### ISSUE THREAD

**Issue by hartwoolery** [MyCometG3/DLAB#1]
Hi, 

Would it be possible to add a key to the dictionary in DLABDevice+Input.mm (see my fork [here](https://github.com/hartwoolery/DLAB))

`NSString* surfaceKey = (__bridge NSString *)kCVPixelBufferIOSurfacePropertiesKey;`
`...`
`pbAttributes[surfaceKey] = @(1);`

This key allows us to create a MTLTexture from the resulting CVPixelBuffer

Thank you for this wonderful wrapper, it has almost worked perfectly for my use case.

**Comment by MyCometG3** [comment]
Thank you for your report.

Something I need to consider are following:
1. kCVPixelBufferIOSurfacePropertiesKey takes CFDictionaryRef, and empty dictionary will declare as IOSurface compatible.
2. DLAB native kCVPixelBufferBytesPerRowAlignmentKey is 16, which provides vast compatibility with most of CVPixelFormat.
3. MTLTexture buffer alignment could be large than 16, and it varies based on MTLPixelFormat.
4. IOSurface itself accepts alignment 16 though, additional MTL operation may require larger CVPixelBuffer alignment, like 32, 64, or 128.

So I would like to consider following. Does it meet your requirement?
- Add new NSMutableDictionary property to DALBDevice, which contains following by default:
    kCVPixelBufferBytesPerRowAlignmentKey=16;
    kCVPixelBufferIOSurfacePropertiesKey=[NSDictionary new];
- DLAB will apply it to pbProperties for CVPixelBufferPool(input) on initialization step.
- Caller can explicitly modify the property (before start) with any CVPixelBufferPropertyKeys and values
- If kCVPixelBufferBytesPerRowAlignmentKey is not defined, alignement will be depends on GPU texture native value.

NOTE: Some open source library uses multiple combination, It may or may not work with specified pixel format though:
1. Only kCVPixelBufferMetalCompatibilityKey=TRUE
2. kCVPixelBufferMetalCompatibilityKey+kCVPixelBufferBytesPerRowAlignmentKey=widthOfImage
3. kCVPixelBufferMetalCompatibilityKey+ kCVPixelBufferOpenGLCompatibilityKey+ kCVPixelBufferIOSurfacePropertiesKey

**Comment by MyCometG3** [comment]
Implemented. Please try.

**Comment by hartwoolery** [comment]
It works, thank you!

**Comment by hartwoolery** [comment]
It works, thank you!
